### ISSUE TITLE
skywaling agent启动arthas出错

### ISSUE THREAD

**Issue by jiaguoyi** [weixiang1862/skywalking-x-arthas#11]
<img width="953" alt="捕获" src="https://github.com/user-attachments/assets/8801b6ef-65f2-48eb-af5e-0a9a1965b4b3">
作者你好，这种报错是啥原因造成的呀

**Comment by weixiang1862** [comment]
![image](https://github.com/user-attachments/assets/18a4e094-1194-4f7a-885c-7b4c2dcfd67f)

可以到arthas issues下面搜索看看，这些可能对你有帮助。
