### ISSUE TITLE
arthas页面中$ServiceInstance的值是怎么生成的？

### ISSUE THREAD

**Issue by jiaguoyi** [weixiang1862/skywalking-x-arthas#12]
<img width="934" alt="sky" src="https://github.com/user-attachments/assets/fb32a2d0-dd97-4901-97b5-0d6e3e6262b2">

java -javaagent:D:\tools\skywalking\skywalking-agent\skywalking-agent.jar -Dskywalking.agent.service_name=arthas -Dskywalking.collector.backend-service=127.0.0.1:12800 -jar arthas-test-1.0-SNAPSHOT.jar，arthas-test-1.0-SNAPSHOT.jar 这个springboot项目中添加arthas-test-1.0-SNAPSHOT.jar的依赖吗，配置文件中需要配置arthas.agent-id吗?

**Comment by jiaguoyi** [comment]
<img width="630" alt="配置" src="https://github.com/user-attachments/assets/93752c0a-7785-4c0b-b022-dfdf429cb352">
我在代码中是这么配置agent-id的，
<img width="878" alt="sky" src="https://github.com/user-attachments/assets/1c778f21-ed0e-4c10-885d-504465957d53">
使用$ServiceInstance的值调用报错了，报下图中的错误，作者您能给解答一下吗？
<img width="953" alt="捕获" src="https://github.com/user-attachments/assets/11dc046f-3c16-4370-bacd-951d90fe156c">

**Comment by jiaguoyi** [comment]
<img width="938" alt="tunnel" src="https://github.com/user-attachments/assets/dfc96943-bd5c-4c71-8c96-eb84a5a89d38">

**Comment by weixiang1862** [comment]
`-agent-id`用到的skywalking的instanceId去注册的，可以通过skywalking配置文件定义instance名称

![image](https://github.com/user-attachments/assets/d54a85d3-8111-479d-93ee-8a5ff8b27639)

**Comment by jiaguoyi** [comment]
魏老师，agent arthas-control-plugin， oap arthas-controller-module，skywalking-webapp这三个jar包的源码能提供我们看一下吗，我们想在这个基础上再做一些扩展，然后扩展完了之后也给您共享一下

**Comment by weixiang1862** [comment]
> 魏老师，agent arthas-control-plugin， oap arthas-controller-module，skywalking-webapp这三个jar包的源码能提供我们看一下吗，我们想在这个基础上再做一些扩展，然后扩展完了之后也给您共享一下

所有代码都在这里，https://github.com/weixiang1862/skywalking-x-arthas

**Comment by jiaguoyi** [comment]
谢谢魏老师
