### ISSUE TITLE
不展示arthas图标

### ISSUE THREAD

**Issue by jmyinjg** [weixiang1862/skywalking-x-arthas#3]
你好，我按照教程部署好之后，skywalking ui 不展示 arthas图标，请问是什么情况 skywalking 9.6 agent 9.0版本
![image](https://github.com/weixiang1862/skywalking-x-arthas/assets/22140878/48ea2200-a375-44e4-bb19-4b9b0cf670be)

**Comment by weixiang1862** [comment]
我更新了dist下的skywalking-webapp.jar，你更新下再试试。

**Comment by jmyinjg** [comment]
@weixiang1862 现在可以显示出来了，但是接口报405， arthas-controller-module这个模块已经加载了。。。
![image](https://github.com/weixiang1862/skywalking-x-arthas/assets/22140878/20805a3b-2fb6-4452-9a8e-0584236e2d0c)

**Comment by weixiang1862** [comment]
> @weixiang1862 现在可以显示出来了，但是接口报405， arthas-controller-module这个模块已经加载了。。。 

再更新下webapp，我fix了

**Comment by jmyinjg** [comment]
可以了，谢谢
