### ISSUE TITLE
请问下载的arthas-tunnel-server-3.7.1.jar是放到arthas目录下启动嘛？还是随便放到啥目录都可以？

### ISSUE THREAD

**Issue by cfy3133** [weixiang1862/skywalking-x-arthas#5]
请问下载的arthas-tunnel-server-3.7.1.jar是放到arthas目录下启动嘛？还是随便放到啥目录都可以？

**Comment by weixiang1862** [comment]
> 请问下载的arthas-tunnel-server-3.7.1.jar是放到arthas目录下启动嘛？还是随便放到啥目录都可以？

任意目录

**Comment by cfy3133** [comment]
好的，谢谢，另外请问下，plugin.arthas.tunnel_server=${SW_ARTHAS_TUNNEL_SERVER:ws://127.0.0.1:7777/ws}
plugin.arthas.session_timeout=${SW_ARTHAS_SESSION_TIMEOUT:}
plugin.arthas.disabled_commands=${SW_ARTHAS_DISABLED_COMMAND:}
这几个变量中SW_ARTHAS_TUNNEL_SERVER、SW_ARTHAS_SESSION_TIMEOUT、SW_ARTHAS_DISABLED_COMMAND按照教程里面默认的就可以了嘛

**Comment by weixiang1862** [comment]
> plugin.arthas.tunnel_server=${SW_ARTHAS_TUNNEL_SERVER:ws://127.0.0.1:7777/ws}

**plugin.arthas.tunnel_server**

如果tunnel-server地址和agent部署在一台机器上，用默认值就可以，如果不是，这里要填实际的ip端口

**plugin.arthas.session_timeout**

这个变量控制arthas会话超时时间，可以用默认的

**plugin.arthas.disabled_commands**

这个变量用来配置需要禁用哪些arthas command，无特殊需要，用默认即可

**Comment by cfy3133** [comment]
好的，谢谢作者耐心回答，好像还有一个，plugin.arthas.arthas_home=${SW_ARTHAS_HOME:}中的SW_ARTHAS_HOME也是默认的嘛

**Comment by weixiang1862** [comment]
> 好的，谢谢作者耐心回答，好像还有一个，plugin.arthas.arthas_home=${SW_ARTHAS_HOME:}中的SW_ARTHAS_HOME也是默认的嘛

默认会在 ${skywalking_agent_home}/arthas 这个目录下寻找arthas，也可以指定别的目录。

**Comment by cfy3133** [comment]
好嘞，谢谢
