### ISSUE TITLE
作者你好，我用docker-compose安装的oap，想进入oap容器中把skywalking-webapp.jar使用cp dist/skywalking-webapp.jar ${your_oap_server_home}/webapp/复制到webapp中，但是发现没有这个目录

### ISSUE THREAD

**Issue by cfy3133** [weixiang1862/skywalking-x-arthas#6]

**Comment by cfy3133** [comment]
![7421171e6546468c657e6bc83320965](https://github.com/weixiang1862/skywalking-x-arthas/assets/43978367/6cc35bcc-45bc-467c-a736-f51e2d3fe54b)

**Comment by cfy3133** [comment]
skywalking也正常启动了，而且服务器也存在oap-libs这个目录，就是看不到webapp目录，作者知道为啥嘛

**Comment by weixiang1862** [comment]
这个是skywalking-oap-server的镜像，skywalking-webapp.jar 需要复制到 skywalking-ui 容器中：
![image](https://github.com/weixiang1862/skywalking-x-arthas/assets/16346644/e3279f4e-aa77-4321-b1ed-10b20680318f)

**Comment by cfy3133** [comment]
谢谢哈，找到了
