### ISSUE TITLE
skywalking ui链接arthas 返回200但是不显示内容

### ISSUE THREAD

**Issue by rookie-fpc** [weixiang1862/skywalking-x-arthas#8]
作者你好，我的arthas tunnel server跟java agent部署在不同的服务器上，我用skywalking ui链接时是这么配的：
![image](https://github.com/weixiang1862/skywalking-x-arthas/assets/75996252/f3356b92-e62f-45e9-ae8e-5db602211d15)

tunnel server的日志：
![image](https://github.com/weixiang1862/skywalking-x-arthas/assets/75996252/2b1b6e6b-1663-46d6-b2ab-21ffbdebde07)

java agent的日志：
![image](https://github.com/weixiang1862/skywalking-x-arthas/assets/75996252/75ad17a8-40c9-4f10-a61f-6a8cc679ee4d)

skywalking UI页面返回200，但是没有显示，请问下可能是什么原因呢
![image](https://github.com/weixiang1862/skywalking-x-arthas/assets/75996252/bd175fcf-347e-416c-afa1-71f0fb4aa44c)

**Comment by rookie-fpc** [comment]
skywalking版本：9.7.0
java agent版本： 8.16.0
服务器上的java版本：17.0.7

**Comment by weixiang1862** [comment]
看日志arthas attach成功了，也连接到tunnel-server上了，看下F12 console有没有报错

**Comment by rookie-fpc** [comment]
> 看日志arthas attach成功了，也连接到tunnel-server上了，看下F12 console有没有报错

多谢多谢，问题已经解决
